def open_order(table_number: int) -> dict: ...
def add_item_to_order(order: dict, menu_item: dict, quantity: int, note:
str = "") -> dict: ...
def remove_item_from_order(order: dict, item_id: str) -> dict: ...
def update_item_status(order: dict, item_id: str, status: str) -> dict:
...
def calculate_bill(order: dict, tax_rate: float, tip_rate: float) -> dict:
...
def split_bill(order: dict, method: str, parties: int | list[int]) ->
list[dict]: ...
#bunları proje dosyasından geçirdim, henüz bu dosyaya bakmış değilim
