def load_state(data_dir: str) -> tuple[list, dict, list]: ...
def save_state(data_dir: str, tables: list, menu: dict, orders: list) ->
None: ...
def backup_day(data_dir: str, archive_dir: str) -> str: ...
def log_kitchen_ticket(order: dict, directory: str) -> str: ...
#bunları proje dosyasından geçirdim, henüz bu dosyaya bakmış değilim
